In [8]:
# Import modules
import pandas as pd
from IPython.display import display

In [9]:
# Read in data
policy_df = pd.read_csv("../policies.csv")
claims_df = pd.read_csv("../claims.csv")

In [10]:
# Display the first few rows of the dataframes
display(policy_df.head(5))
display(claims_df.head(5))

  policy_number colour  vehicle_value_at_new  vehicle_age  annual_mileage
0      POL#0001    Red                 31014            8            9287
1      POL#0002    Red                  1808            1           12804
2      POL#0003    Red                 22298           14            4913
3      POL#0004    Red                 20056            5            6671
4      POL#0005  Black                 19953            1            7919

  claim_number policy_number  claim_amount
0     CLM#0001      POL#1609         47.97
1     CLM#0002      POL#0700         36.71
2     CLM#0003      POL#0700        210.82
3     CLM#0004      POL#1794        298.43
4     CLM#0005      POL#1599        212.53